### ISSUE TITLE
Update CPAN module

### ISSUE THREAD

**Issue by mdjunior** [zurborg/libwww-hkp-perl#2]
Hi David Zurborg,

Can you please update your cpan module for this last version?

I'm trying to use this module but the most recent version on Github uses the regex /^pub:([0-9a-f]{8,40}):(\d_):(\d_):(\d_):(\d_):([der]_)$/i and the oldest version is using  /^pub:([0-9a-f]{8,16}):(\d_):(\d_):(\d_):(\d_):([der]_)$/ . That is causing me incompatibility problems with new SKS Key servers.

Thanks a lot,
Manoel

**Comment by zurborg** [comment]
Can you provide an example, in which cases the newer regex cause problems?

**Comment by mdjunior** [comment]
The problem is in the old regex, so I would like the module (version 0.02 on CPAN) was updated...

**Comment by zurborg** [comment]
Oh, oh, I see... erm... I going to update the CPAN module as soon as possible :-)
